version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env.postgres
    ports:
      - "8001:5432"

  project:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - .env.project
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  nginx:
    image: nginx:latest
    volumes:
      - ../conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - project

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A myshop worker --loglevel=info -P eventlet
    depends_on:
      - redis
      - postgres-db
    env_file:
      - .env.project
    volumes:
      - static_volume:/code/static

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  static_volume:
  media_volume: